version: "3.9"

services:
  #Node.js API service
  api:
    container_name: api_container
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DATABASE_URL: mongodb://mongo_db:27017/kitchenMate
    depends_on:
      - mongo_db


  #MongoDB services
  mongo_db:
    container_name: db_container
    image: mongo:latest
    restart: always
    volumes:
      - kitchenMate:/data/db

volumes:
  kitchenMate: {}